name: '${name}'
version: '${version}'
main: '${main}'
description: 'RSPlugin - ${name}'
api-version: '${api_version}'
depend: [ RSFramework, LuckPerms, DiscordSRV ]
softdepend: [ Essentials, CMI ]
authors: [ '${author}' ]